spring:
  application:
    name: queue-management-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/queue_management_platform
    username: postgres
    password: Ahmed2002

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false